### ISSUE TITLE
Confused!

### ISSUE THREAD

**Issue by amrrs** [njtierney/mypraise#1]
Hey, if you don't mind - Is this a fun project? or something to explain package creation with `glue` functions? or just to simply praiseme?

**Comment by njtierney** [comment]
Hello! This package was used for demonstration purposes for teaching a workshop. It helped explain `glue` as well, to help explain adding packages for teaching. But it isn't a serious package.

Hope that answers your question :)

**Comment by amrrs** [comment]
Thank you @njtierney for the response! The explanation helps!
